server:
  port: 8001 # ?? ??
  servlet:
    context-path: / # root ?? ??
    encoding: # ??? ??
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: prod
  resources:
    cache:
      period: 0
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false