server:
  port: 8001 # ?? ??
  servlet:
    context-path: / # root ?? ??
    encoding: # ??? ??
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: prod
  thymeleaf:
    cache: 'false'
  freemarker:
    cache: 'false'
  devtools:
    livereload:
      enabled: 'true'