server:
  port: 8001 # ?? ??
  servlet:
    context-path: / # root ?? ??
    encoding: # ??? ??
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: prod
  thymeleaf:
    cache: 'false'
  freemarker:
    cache: 'false'
  devtools:
    livereload:
      enabled: 'true'

    # spring data jpa 설정
    jpa:
      database-platform: org.hibernate.dialect.MySQL57Dialect
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: update