server:
  port: 8001 # ?? ??
  servlet:
    context-path: / # root ?? ??
    encoding: # ??? ??
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: prod
  thymeleaf:
    cache: 'false'
  freemarker:
    cache: 'false'
  devtools:
    livereload:
      enabled: 'true'

    # spring data jpa 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate: info

spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
